# Generated by Django 4.2.1 on 2023-05-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='stock',
            new_name='quantity',
        ),
    ]
